### PR TITLE
improve setup for a more production ready workload

### PR DESCRIPTION
**Pull request by anubisg1**
- split gui, poller and rest into separate pods
- use env variables where needed
- poller configured as a statefulset
- use ingress to expose suzieq webui and rest server
- updated configuration files to match current suzieq requirements and showing multiple namespaces
- use official suzieq image

### CODE REVIEW

**Comment by bitcollector1** [comment]
Thanks folks, this has been a perfect project to get me introduced to K8, really appreciate the updates to support the newest version of suzieq!

**Comment by bitcollector1** [comment]
I was able to follow the last example, this one has WAY too many bells and whistles for me to bring up any pods. Worse, when I asked for some focused trainings at out team meeting yesterday I got laughed at...........might be time to find a new place of employment :(

**Comment by bitcollector1** [comment]
I did manage to find a couple of typos, one of them in is gui.yml  
```
 image: docker pull netenglabs/suzieq:0.17.0
```

**Comment by bitcollector1** [comment]
also, from what I can tell secrets.yml  is missing the name 
```
metadata:
  name: sq-credentials
```

**Comment by bitcollector1** [comment]
now if I can just get this pod affinity and taint crap figured out.....lol.......this really is a great example to learn from.....just painful as a newbie to K8 :(

**Comment by anubisg1** [comment]
> I did manage to find a couple of typos, one of them in is gui.yml
> 
> ```
>  image: docker pull netenglabs/suzieq:0.17.0
> ```

Fixed, dumb typo, sorry

**Comment by anubisg1** [comment]
> also, from what I can tell secrets.yml is missing the name
> 
> ```
> metadata:
>   name: sq-credentials
> ```

Fixed that, only needed the metadata.name

Those errors come from copy/pasting.

**Comment by anubisg1** [comment]
> now if I can just get this pod affinity and taint crap figured out.....lol.......this really is a great example to learn from.....just painful as a newbie to K8 :(

What I have is just podAffinity to make sure that pods start up in the same node. The reason is because the storage is read write once. If you have a storage that allows read write many, then you don't really need that part

**Comment by anubisg1** [comment]
> I was able to follow the last example, this one has WAY too many bells and whistles for me to bring up any pods. Worse, when I asked for some focused trainings at out team meeting yesterday I got laughed at...........might be time to find a new place of employment :(

Try with

```
Kubectl apply -f . -n namespace_name
```

;-)

**Comment by bitcollector1** [comment]
so my pod starts and stops after a few seconds with this
```
[root@kube4 suzieq-0.17.0]# kubectl logs pod/sq-gui-deploy-54cf87f66f-kz8b4
ERROR: Invalid config file: /home/suzieq/.suzieq/suzieq-cfg.yml
FATAL: Data directory ./parquet is not an acceesible dir
```

any clues? I've been at it pretty much all day, lol.

**Comment by bitcollector1** [comment]
FYI, we are bare metal cluster and I'm using the same storage that was previously working with 0.16.0

**Comment by anubisg1** [comment]
> so my pod starts and stops after a few seconds with this
> 
> ```
> [root@kube4 suzieq-0.17.0]# kubectl logs pod/sq-gui-deploy-54cf87f66f-kz8b4
> ERROR: Invalid config file: /home/suzieq/.suzieq/suzieq-cfg.yml
> FATAL: Data directory ./parquet is not an acceesible dir
> ```
> 
> any clues? I've been at it pretty much all day, lol.

Yes I think I know the reason. App starts as user suzieq but volume is mounted as root.  This is fixed by adding fsgroup under the security context, give me a moment I'll add that.

**Comment by anubisg1** [comment]
> > so my pod starts and stops after a few seconds with this
> > ```
> > [root@kube4 suzieq-0.17.0]# kubectl logs pod/sq-gui-deploy-54cf87f66f-kz8b4
> > ERROR: Invalid config file: /home/suzieq/.suzieq/suzieq-cfg.yml
> > FATAL: Data directory ./parquet is not an acceesible dir
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > any clues? I've been at it pretty much all day, lol.
> 
> Yes I think I know the reason. App starts as user suzieq but volume is mounted as root. This is fixed by adding fsgroup under the security context, give me a moment I'll add that.

Turns out that it's already there. Can you make sure that you got the latest manifests?

**Comment by anubisg1** [comment]
> > The reason is because the storage is read write once. If you have a storage that allows read write many, then you don't really need that part
> 
> FWIW Previously when I did the initial set of manifests, the private cluster I was working on only had R/W once. That drove alot of choices that I would have done otherwise if I had access to R/W many.
> 
> In the past I have generally used EKS for my testing, I have a mostly working workflow for deploying eks with efs for R/W many. I just haven't had the time to sit down and deploy it. I need to make some adjustments to the terraform plan I have.
> 
> But I have also been spending alot of time trying to ramp up on Azure so I keep punting on it.

We are using Azure AKS. The problem is that Azure files have an issue with a lot of small files, so using that as read write many wasn't an option (too slow), therefore we enforce podAffinity and read write once

**Comment by anubisg1** [comment]
Here is why we got that

https://github.com/Azure/AKS/issues/223

**Comment by bitcollector1** [comment]
pretty sure I have the lastest files.....I'm just focused on gui.yaml currently   here is that snippet 

```
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: group
                operator: In
                values:
                  - suzieq
            topologyKey: "kubernetes.io/hostname"
```

**Comment by bitcollector1** [comment]
I'm tapping out......I'll watch this space to see if anyone else runs into the same issues as my snowflake.

**Comment by bitcollector1** [comment]
looks like I am closer, managed to get rid of the other error 
```
[root@kube4 suzieq-0.17.0]# kubectl logs pod/sq-gui-deploy-5bb5445788-qcthb
suzieq requires a configuration file either in ./suzieq-cfg.yml or ~/.suzieq/suzieq-cfg.yml
```

**Comment by anubisg1** [comment]
I know what's causing the problems. I just checked my prod manifests. I'll patch it soon, sorry

**Comment by bitcollector1** [comment]
I added to the security context.  
```
runAsUser: 0
```
 and it got rid of one of the errors
```
[root@kube4 suzieq-0.17.0]# kubectl logs pod/sq-gui-deploy-54cf87f66f-2j9k6
ERROR: Invalid config file: /home/suzieq/.suzieq/suzieq-cfg.yml
FATAL: Data directory /home/suzieq/parquet is not an acceesible dir
```

**Comment by anubisg1** [comment]
> 

that is 100% wrong. you are basically running as root!

**Comment by bitcollector1** [comment]
that's I I usually fix all my permission issues 777 and work backwards from that...HA!

**Comment by bitcollector1** [comment]
subpath, nice!  I was playing with that all day since it was in my old config files. Appreciate the updates!

**Comment by anubisg1** [comment]
what version of kubernetes are you running?  microk8s, k3s?

**Comment by anubisg1** [comment]
can you try now, make sure you use the orginal manifests, do NOT use "runAsUser: 0"

**Comment by bitcollector1** [comment]
running v1.23.1 K8 and also messing with minikube

**Comment by bitcollector1** [comment]
looks like poller.yml needs some linting.  This site worked for me....still fighting with sublime yaml linter :( 
https://jsonformatter.org/yaml-validator

```
[root@kube4 suzieq-0.17.0]# kubectl delete -f poller.yaml
service "sq-poller-headless" deleted
error: error parsing poller.yaml: error converting YAML to JSON: yaml: line 35: did not find expected '-' indicator
```

might have been a copy paste error on my end, IDK.

**Comment by anubisg1** [comment]
> looks like poller.yml needs some linting. This site worked for me....still fighting with sublime yaml linter :( https://jsonformatter.org/yaml-validator
> 
> ```
> [root@kube4 suzieq-0.17.0]# kubectl delete -f poller.yaml
> service "sq-poller-headless" deleted
> error: error parsing poller.yaml: error converting YAML to JSON: yaml: line 35: did not find expected '-' indicator
> ```
> 
> might have been a copy paste error on my end, IDK.

let me deploy this on my microk8s cluster, one sec i'll push any changes necessary

**Comment by bitcollector1** [comment]
I've got to be fighting some permission issues somewhere, still this same old error over and over again after removing runuser 0
```
[root@kube4 suzieq-0.17.0]# kubectl logs pod/sq-poller-0
ERROR: Invalid config file: /home/suzieq/.suzieq/suzieq-cfg.yml
FATAL: Data directory ./parquet is not an acceesible dir
```

**Comment by bitcollector1** [comment]
```
[root@kube4 suzieq-0.17.0]# kubectl get all
NAME                                            READY   STATUS              RESTARTS      AGE
pod/iperf3-clients-5jmk9                        1/1     Running             0             8d
pod/iperf3-clients-crfl5                        0/1     ContainerCreating   0             7d14h
pod/iperf3-clients-fpxx4                        1/1     Running             0             8d
pod/iperf3-clients-kbh85                        1/1     Running             0             8d
pod/iperf3-clients-kjfbq                        1/1     Running             0             8d
pod/iperf3-clients-lft6k                        1/1     Running             0             8d
pod/iperf3-clients-s9gwm                        1/1     Running             0             8d
pod/iperf3-clients-xb8rx                        1/1     Running             0             8d
pod/iperf3-server-deployment-5cb8588d7d-v2mmk   1/1     Running             0             3d7h
pod/mongo-p3efg7-0                              1/1     Running             0             3d5h
pod/nginx-85b98978db-56pnh                      1/1     Running             0             59d
pod/sq-gui-deploy-674f644bc6-k92dg              0/1     CrashLoopBackOff    5 (72s ago)   5m10s
pod/sq-poller-0                                 0/1     CrashLoopBackOff    5 (97s ago)   5m8s
pod/sq-rest-deploy-7f485f66b5-hfrh5             0/1     CrashLoopBackOff    5 (85s ago)   5m6s

NAME                         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)           AGE
service/iperf3-server        ClusterIP   10.97.29.212     <none>        5201/TCP          8d
service/kubernetes           ClusterIP   10.96.0.1        <none>        443/TCP           106d
service/mongo-p3efg7-0       NodePort    10.107.83.120    <none>        27017:30365/TCP   14d
service/nginx                NodePort    10.104.235.163   <none>        80:31292/TCP      102d
service/sq-gui-service       NodePort    10.103.204.111   <none>        80:30080/TCP      5m10s
service/sq-poller-headless   ClusterIP   None             <none>        <none>            5m8s
service/sq-rest-service      NodePort    10.107.92.105    <none>        80:30081/TCP      5m6s

NAME                            DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/iperf3-clients   8         8         7       8            7           <none>          8d

NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/iperf3-server-deployment   1/1     1            1           8d
deployment.apps/nginx                      1/1     1            1           102d
deployment.apps/sq-gui-deploy              0/1     1            0           5m10s
deployment.apps/sq-rest-deploy             0/1     1            0           5m6s

NAME                                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/iperf3-server-deployment-5cb8588d7d   1         1         1       8d
replicaset.apps/nginx-85b98978db                      1         1         1       102d
replicaset.apps/sq-gui-deploy-674f644bc6              1         1         0       5m10s
replicaset.apps/sq-rest-deploy-7f485f66b5             1         1         0       5m6s

NAME                            READY   AGE
statefulset.apps/mongo-p3efg7   1/1     14d
statefulset.apps/sq-poller      0/1     5m8s
```

**Comment by anubisg1** [comment]
just hold on a minute :) let me check a couple of things .

**Comment by anubisg1** [comment]
i think that all you need is to check your storageclass... 

can you show me the output of  "kubectl get storageclass" 

```
admin@aks-node-0:~/suzieq-on-k8s$ kubectl get storageclass
NAME                PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
microk8s-hostpath   microk8s.io/hostpath   Delete          Immediate           false                  37d
nfs-csi (default)   nfs.csi.k8s.io         Delete          Immediate           false                  27d
```

**Comment by bitcollector1** [comment]
Using manual storage currently 
```
[root@kube4 suzieq-0.17.0]# kubectl get storageclass
No resources found
```

```
[root@kube4 suzieq-0.17.0]# kubectl get pv parquet
NAME      CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                 STORAGECLASS   REASON   AGE
parquet   1000Gi     RWX            Retain           Bound    default/parquet-pvc   manual                  2m19s
```

```
[root@kube4 suzieq-0.17.0]# kubectl get pvc parquet-pvc
NAME          STATUS   VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS   AGE
parquet-pvc   Bound    parquet   1000Gi     RWX            manual         2m43s
```

**Comment by bitcollector1** [comment]
```
[root@kube4 suzieq-0.17.0]# kubectl describe pvc parquet-pvc
Name:          parquet-pvc
Namespace:     default
StorageClass:  manual
Status:        Bound
Volume:        parquet
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      1000Gi
Access Modes:  RWX
VolumeMode:    Filesystem
Used By:       sq-gui-deploy-674f644bc6-dlfmf
               sq-poller-0
               sq-rest-deploy-7f485f66b5-5zklc
Events:        <none>
```

**Comment by bitcollector1** [comment]
```
[root@kube4 suzieq-0.17.0]# kubectl describe pv parquet
Name:            parquet
Labels:          type=local
Annotations:     pv.kubernetes.io/bound-by-controller: yes
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    manual
Status:          Bound
Claim:           default/parquet-pvc
Reclaim Policy:  Retain
Access Modes:    RWX
VolumeMode:      Filesystem
Capacity:        1000Gi
Node Affinity:   <none>
Message:         
Source:
    Type:          HostPath (bare host directory volume)
    Path:          /home/suzieq
    HostPathType:  
Events:            <none>
```

**Comment by anubisg1** [comment]
ok, that is a weird setup you have there... 
i fully tested the manifests now and i know they work.

in my example:

1) i have two storage classes definied.  one is NFS shared storage class, and the other is a single node disk "microk8s-hostpath"
2) i know i have permission issues on the NFS side so i use microk8ts-hostpath in this example and i do that by editing the pvc manifest

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: parquet-pvc
spec:
  storageClassName: microk8s-hostpath    <<<<--- HERE 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
```

i then apply all manifests:

```
admin@aks-node-0:~/suzieq-on-k8s/manifest$ kubectl create namespace suzieq
namespace/suzieq created
admin@aks-node-0:~/suzieq-on-k8s/manifest$ kubectl apply -f . -n suzieq
configmap/sq-inventory created
configmap/sq-conf created
deployment.apps/sq-gui-deploy created
service/sq-gui-service created
ingress.networking.k8s.io/suzieq-ingress created
service/sq-poller-headless created
statefulset.apps/sq-poller created
persistentvolumeclaim/parquet-pvc created
deployment.apps/sq-rest-deploy created
service/sq-rest-service created
secret/sq-credentials created
```


everything works:

```
admin@aks-node-0:~/suzieq-on-k8s/manifest$ kubectl get all -n suzieq
NAME                                  READY   STATUS    RESTARTS   AGE
pod/sq-gui-deploy-674f644bc6-8r2m5    1/1     Running   0          43s
pod/sq-poller-0                       1/1     Running   0          43s
pod/sq-rest-deploy-7f485f66b5-78cjm   1/1     Running   0          42s

NAME                         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
service/sq-gui-service       NodePort    10.152.183.23    <none>        80:30080/TCP   43s
service/sq-poller-headless   ClusterIP   None             <none>        <none>         43s
service/sq-rest-service      NodePort    10.152.183.140   <none>        80:30081/TCP   42s

NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/sq-gui-deploy    1/1     1            1           43s
deployment.apps/sq-rest-deploy   1/1     1            1           43s

NAME                                        DESIRED   CURRENT   READY   AGE
replicaset.apps/sq-gui-deploy-674f644bc6    1         1         1       43s
replicaset.apps/sq-rest-deploy-7f485f66b5   1         1         1       43s

NAME                         READY   AGE
statefulset.apps/sq-poller   1/1     43s


admin@aks-node-0:~/suzieq-on-k8s/manifest$ kubectl logs sq-poller-0  -n suzieq
2022-04-08 08:08:36,665 - suzieq.poller.controller - WARNING - log level WARNING


admin@aks-node-0:~/suzieq-on-k8s/manifest$ kubectl logs sq-gui-deploy-674f644bc6-8r2m5  -n suzieq

  Starting Suzieq GUI
2022-04-08 08:08:46.640 INFO    matplotlib.font_manager: generated new fontManager

  You can now view your Streamlit app in your browser.

  Network URL: http://10.1.7.231:8501
  External URL: http://xx.xx.xx.xx:8501


admin@aks-node-0:~/suzieq-on-k8s/manifest$ kubectl logs sq-rest-deploy-7f485f66b5-78cjm  -n suzieq
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
```

**Comment by bitcollector1** [comment]
nice work! I appreciate all your efforts.....yeah, I inherited this cluster#*ck from the guy we fired ;)  Trying to come up to speed but there is so much depth and I'm just getting started.

**Comment by anubisg1** [comment]
after fixing my NFS share, it works over there too without problems

```
admin@aks-node-0:~/suzieq-on-k8s/manifest$ kubectl get pvc -n suzieq
NAME          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
parquet-pvc   Bound    pvc-ef00660c-a31e-4208-911c-a6dbcd30c802   5Gi        RWO            nfs-csi        61s


admin@aks-node-0:~/suzieq-on-k8s/manifest$ kubectl get pod -n suzieq
NAME                              READY   STATUS    RESTARTS   AGE
sq-gui-deploy-674f644bc6-dd8tb    1/1     Running   0          64s
sq-poller-0                       1/1     Running   0          63s
sq-rest-deploy-7f485f66b5-576cn   1/1     Running   0          63s


admin@aks-node-0:~/suzieq-on-k8s/manifest$ kubectl logs sq-poller-0 -n suzieq
2022-04-08 08:13:18,144 - suzieq.poller.controller - WARNING - log level WARNING
```


therefore i would suggest:

1) use the manifest as they are, you only need change the configmap if there is anything you need to change, but for testing you don't need to change anything at all
2) ensure that you kubernetes cluster is configured appropriately in regarding of storage and storageclasses

**Comment by bitcollector1** [comment]
Looks like the storage is the issue now,  no more pods crashing
```
<invalid>   Warning   FailedMount         pod/sq-gui-deploy-6dd9fd9f89-ck5jr     MountVolume.SetUp failed for volume "sq-conf" : configmap "sq-conf" not found
<invalid>   Warning   FailedMount         pod/sq-poller-0                        MountVolume.SetUp failed for volume "inventory" : configmap "sq-inventory" not found
<invalid>   Warning   FailedMount         pod/sq-poller-0                        MountVolume.SetUp failed for volume "sq-conf" : configmap "sq-conf" not found
<invalid>   Warning   FailedMount         pod/sq-rest-deploy-7f485f66b5-2fd8d    MountVolume.SetUp failed for volume "sq-conf" : configmap "sq-conf" not found
```

```
[root@kube4 manifest]# kubectl get all -n suzieq
NAME                                  READY   STATUS              RESTARTS   AGE
pod/sq-gui-deploy-6dd9fd9f89-ck5jr    0/1     ContainerCreating   0          4m3s
pod/sq-poller-0                       0/1     ContainerCreating   0          4m3s
pod/sq-rest-deploy-7f485f66b5-2fd8d   0/1     ContainerCreating   0          4m2s

NAME                         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
service/sq-gui-service       NodePort    10.98.85.55      <none>        80:30080/TCP   4m3s
service/sq-poller-headless   ClusterIP   None             <none>        <none>         4m3s
service/sq-rest-service      NodePort    10.105.205.132   <none>        80:30081/TCP   4m2s

NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/sq-gui-deploy    0/1     1            0           4m3s
deployment.apps/sq-rest-deploy   0/1     1            0           4m3s

NAME                                        DESIRED   CURRENT   READY   AGE
replicaset.apps/sq-gui-deploy-6dd9fd9f89    1         1         0       4m3s
replicaset.apps/sq-rest-deploy-7f485f66b5   1         1         0       4m3s

NAME                         READY   AGE
statefulset.apps/sq-poller   0/1     4m3s
```

**Comment by anubisg1** [comment]
did you apply the configmaps??

`kubectl get configmap -n suzieq`

**Comment by bitcollector1** [comment]
Thanks again for everything, pretty sure I can get this last issue figured out. I learned sooooo much today!

**Comment by bitcollector1** [comment]
apparently I did not....thought it would be built with the one command if I chucked it into the manifest folder but it appears it did not.....so thanks again.....I owe you a few beers ;) 
```
[root@kube4 manifest]# kubectl get configmap
NAME               DATA   AGE
kube-root-ca.crt   1      106d
sq-conf            1      55s
sq-inventory       1      55s
```
```
[root@kube4 manifest]# kubectl get configmap -n suzieq
NAME               DATA   AGE
kube-root-ca.crt   1      37d
```

**Comment by anubisg1** [comment]
> Thanks again for everything, pretty sure I can get this last issue figured out. I learned sooooo much today!

don't worry...

if you just want to test that everything works, follow the "TLDR" section in the readme.
in the issue you just showed me, you didn't apply "configmap.yaml" (or maybe you did in a different namespace).

you can apply all manifests at once (and you should ;) ) .. again, check the quick instructions below


- create a namespace
```
kubectl create namespace suzieq
```
- provide your own certificates or generate a self signed ones
```
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes
kubectl -n suzieq create secret tls suzieq-tls-secret \
  --cert=cert.pem \
  --key=key.pem
```
- deploy suzieq
```
kubectl -n suzieq apply -f manifest/.
kubectl -n suzieq get all
```

**Comment by anubisg1** [comment]
@hyposcaler-bot 

all issues are solved, what's left is just due bitcollector knowledge gap.
please review and merge :)

**Comment by bitcollector1** [comment]
Okay, so the issue was permissions on the worker node where these files were created!  It turns out there was no write permissions by default. Man I'm ready for the weekend now!  Fun times, LOL.

**Comment by bitcollector1** [comment]
I ran into an issue where the poller kept crashing and also seemed to take awhile to get results so I added a second worker and bumped up the resources and things are looking much better now! 

Here was the error I managed to catch
```
root@kube4 suzieq-0.17.0]# kubectl get all -n suzieq
NAME                                  READY   STATUS      RESTARTS   AGE
pod/haproxy                           1/1     Running     0          18h
pod/sq-gui-deploy-b9dd5f6bd-vd9rl     1/1     Running     0          2m53s
pod/sq-poller-0                       0/1     OOMKilled   1          2m52s
pod/sq-rest-deploy-6dc7c876f4-bxcpk   1/1     Running     0          2m52s
```


```
containers:
        - name: poller
          image: netenglabs/suzieq:0.17.1
          command: ["sq-poller", "-I", "inventory.yml", "-w 2"]
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1000Mi"
              cpu: "1000m"
```

**Comment by bitcollector1** [comment]
Last step is to figure out the HA proxy for my bare metal setup, this has been kicking my butt pretty hard. It's so much easier to just use a cloud provider it seems.

**Comment by anubisg1** [comment]
> Last step is to figure out the HA proxy for my bare metal setup, this has been kicking my butt pretty hard. It's so much easier to just use a cloud provider it seems.

That's easy, just install metallb and configure your ingress svc with service type load balancer

**Comment by anubisg1** [comment]
hello @hyposcaler-bot  is there any expectation to merge?

**Pull request closed without merging**
